### ISSUE TITLE
Refactor Specs to become single page and natively generated

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#33]
There's too many clicks to navigate around the site - particularly when deep inside one of the spec in reathedocs.io.  

* Suggest that, in line with IETF/W3C/OASIS common practice for technical specifications we will re-structure the github markdown specs to become one page.
* So then the jekyll plugin will grab the one page, generate a hyperlinked TOC and insert it on the top of the same page and push out an HTML single page spec with TOC as part of ausditital.org native content.  It should also render the header & license stuff consistently.
* Then the  spec will be what you see when you click on one of the spec versions on Ausdigital.org Furthermore, because it has an embedded TOC, there's no need to change the existing left hand navigation panel.
* it would be nice to add a PDF generator so that users can download and print a PDF version if they wish.

**Comment by onthebreeze** [comment]
The standard header for every spec should include:

* Spec ID - will be a URI like ausdigital.org/nry/1.0
* Status - will be a COSS png image URL (Raw/draft/stable/etc)
* Editor - name and github link
* Contributors - list of names & github links.

below that header, generate a table of contents.

Then render the rest of the spec as one page.  use compact line spacing and do not right justify.

try it first with this one https://github.com/ausdigital/ausdigital-nry

**Comment by monkeypants** [comment]
I made ausdigital-nry into a single page BTW, since I'm working on some content issue there

**Comment by kshychko** [comment]
Spec files have been refactored. 
I put different versions (TAP 1.0 and 2.0 for example) under the same repo. 
In order to simplify render process on ausdigital.github.io we now have ast.testpoint.io app, which listens for hooks from spec repositories and updates ausdigital.github.io (at the moment configured to my fork).

Spec structure have been unified for all specs (except order/ship/super):

1. Header
2. Spec name
3. Introduction
4. Goals
5. Status
6. Glossary
7. License
8. Change Process
9. Language
10. %Spec content%
11. Related Material

@onthebreeze , @monkeypants please provide your feedback.
@webilhan , please let me know if the current structure /_specs/%spec_name%/version/index.md works for you.

There are still references to RTD, will be replaced with correct links to ausdigital.org pages once we switch to spec rendering without it.

**Comment by monkeypants** [comment]
my comment to Steve was "I like what Kseniya has done to the front matter on every spec". It's much better.

**Comment by kshychko** [comment]
@webilhan , please add PDF generation.

**Comment by onthebreeze** [comment]
Let's close this and make PDF generation a new ticket.  Good job on the spec generation
